# Funding Configuration for AI Fake Filler
# This file enables GitHub's sponsor button and funding options

github: salekmasudparvez1
# ko_fi: username
# liberapay: username
# custom: ['https://paypal.me/username', 'https://example.com']